### ISSUE TITLE
Select Component Inherits type="text" attribute from Input Component

### ISSUE THREAD

**Issue by at-codes** [GrapesJS/components-forms#47]
https://github.com/GrapesJS/components-forms/blob/6a63e9edb7b085790e90e98acf54accc5f4bd642/src/components.ts#L173-L174

I'm not sure what solution should be applied here. Directly extending the input component is probably not correct. Maybe there should be a common base component that input also extends with the shared attributes from all current input component children? If there isn't much shared then they probably should be separate as they don't share the same tagName.

**Comment by artf** [comment]
Yeah good point, I'll update it
